### PR TITLE
Update for dense bins

### PR DESCRIPTION
**Pull request by Fernal73**
# Existing Sample Changes
## Description

Added additional buffer to fix out put of function dense_histogram.

Added two vector variables dense and sparse in main() to prevent sorted input vector when passed to
function sparse_histogram.

Fixes Issue# 
See above.

## External Dependencies

None. 

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [X] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by praveenkk123** [comment]
@JhaShweta1, can you please review this

**Review by pmpeter1 — COMMENTED** [review]
Is the new code formatted via clang-format -style=google?

**Comment by JhaShweta1** [comment]
As mentioned in oneAPI's libraries documentation-"For better coexistence with the C++ standard library, include oneAPI DPC++ Library (oneDPL) header files before the standard C++ header files." Can you please rearrange the headers accordingly.

**Comment by Fernal73** [comment]
> As mentioned in oneAPI's libraries documentation-"For better coexistence with the C++ standard library, include oneAPI DPC++ Library (oneDPL) header files before the standard C++ header files." Can you please rearrange the headers accordingly.

Thanks, @JhaShweta1 .

I'd appreciate it if you could do this yourself since my fork has gone out of my sync since.

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by praveenkk123** [comment]
> > As mentioned in oneAPI's libraries documentation-"For better coexistence with the C++ standard library, include oneAPI DPC++ Library (oneDPL) header files before the standard C++ header files." Can you please rearrange the headers accordingly.
> 
> Thanks, @JhaShweta1 .
> 
> I'd appreciate it if you could do this yourself since my fork has gone out of my sync since.



> > As mentioned in oneAPI's libraries documentation-"For better coexistence with the C++ standard library, include oneAPI DPC++ Library (oneDPL) header files before the standard C++ header files." Can you please rearrange the headers accordingly.
> 
> Thanks, @JhaShweta1 .
> 
> I'd appreciate it if you could do this yourself since my fork has gone out of my sync since.

@Fernal73  Rearranged the header files in proper order and formatted via clang-format -style=google

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by Fernal73** [comment]
> > > As mentioned in oneAPI's libraries documentation-"For better coexistence with the C++ standard library, include oneAPI DPC++ Library (oneDPL) header files before the standard C++ header files." Can you please rearrange the headers accordingly.
> > 
> > 
> > Thanks, @JhaShweta1 .
> > I'd appreciate it if you could do this yourself since my fork has gone out of my sync since.
> 
> > > As mentioned in oneAPI's libraries documentation-"For better coexistence with the C++ standard library, include oneAPI DPC++ Library (oneDPL) header files before the standard C++ header files." Can you please rearrange the headers accordingly.
> > 
> > 
> > Thanks, @JhaShweta1 .
> > I'd appreciate it if you could do this yourself since my fork has gone out of my sync since.
> 
> @Fernal73 Rearranged the header files in proper order and formatted via clang-format -style=google

Thanks, @praveenkk123 . Any particular reason why rearranging the headers was not needed on devcloud, but was on the build machine?

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Pull request merged**
