### PR TITLE
mv the folder "iLiT-Sample-for-Tensorflow" following new structure.

### PR DESCRIPTION
**Pull request by arthw**
# Description
mv the folder "iLiT-Sample-for-Tensorflow" following new structure.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [X] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [ ] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [ ] Implement coding guidelines and ensure code quality.
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [ ] Adhere to readme template 
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [ ] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

### CODE REVIEW

**Comment by anjgola** [comment]
.gitkeep file is only required if the folder is empty, please remove it when you add files to a folder.

**Review by anjgola — DISMISSED** [review]

**Review by JoeOster — DISMISSED** [review]

**Comment by JoeOster** [comment]
@tomlenth - please verify this is correct path

**Comment by arthw** [comment]
I rebase the code and fix the conflict issue of sample.json

**Review by tomlenth — APPROVED** [review]

**Review by JoeOster — APPROVED** [review]
approved for ci

**Review by JoeOster — APPROVED** [review]
approving for ci

**Review by JoeOster — APPROVED** [review]
approved for ci

**Comment by JoeOster** [comment]
@arthw - Please fix your conflict

**Comment by arthw** [comment]
fixed the conflict.

**Comment by JoeOster** [comment]
@arthw 
 - Please take a look at the ci run, you have some issues during ci validation

**Comment by JoeOster** [comment]
@arthw - Please take a look at the error in the log above "#x1B[0;31mNotFoundError#x1B[0m: alexnet_int8_model.pb; No such file or director"

**Comment by arthw** [comment]
@JoeOster 
Yes, I have checked the CI error log of this sample code.
The reason is the iLiT in CI server is upgraded to 1.0.0. The existed code in github is drafted for old iLiT. So the daily CI is always wrong.

In this PR, the code  is changed for new iLiT (1.0.0). So this PR will fix the error in CI log.
So, please approve to trigger CI and test it.

Thank you!

**Review by JoeOster — APPROVED** [review]
approving for ci 

@anjgola please take a look at the Authors latest comments

**Pull request merged**
