### PR TITLE
generate Timeline Json file from oneDNN verbose log

### PR DESCRIPTION
**Pull request by louie-tsai**
# Existing Sample Changes
## Description
New feature for the verbose log tutorial.
generate a timeline json file which users can see oneDNN primitives over timeline via chrome://tracing UI like below diagram. 
Timeline

## External Dependencies

used part of the codes from below project under MIT license.
https://github.com/kwlzn/pytracing
https://github.com/kwlzn/pytracing/blob/master/LICENSE

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X ] New feature (non-breaking change which adds functionality)

## Checklist
Administrative
- [x] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [x] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster
- OSPDT has been informed, approval pending

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [x] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see @JoeOster for assistance) - **pending**
- [x] Bandit Scans (Python only)

Review
- [ ] Tested using Dev Cloud when applicable

### CODE REVIEW

**Review by JoeOster — CHANGES_REQUESTED** [review]
Please take a look at the PR Description, we need several things run. Such as a bandit scan, reviewed etc

**Review by JoeOster — DISMISSED** [review]
approving for ci only

**Comment by louie-tsai** [comment]
Bandit Result : 

image

image

**Comment by louie-tsai** [comment]
> CommandNotFoundError: Your shell has not been properly configured to use 'conda deactivate'.

We don't use conda in those jupyter notebook. 
The issues seems to be inside CI machine instead of the sample.

**Review by JoeOster — DISMISSED** [review]
approved for ci

**Review by JoeOster — APPROVED** [review]
approve for ci

**Review by JoeOster — APPROVED** [review]

**Pull request merged**
