### PR TITLE
Migrate and update matrix_mul_mkl sample

### PR DESCRIPTION
**Pull request by petercad**
# Description

This PR migrates the matrix_mul_mkl sample to the new repo, with a number of code updates/cleanups.

## Type of change

- [X] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

- [X] Command Line

# Checklist for Moving samples:

- [X] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [X] Implement coding guidelines and ensure code quality.
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [X] Adhere to readme template 
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Review DPC++ code with Paul Peterson. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable

### CODE REVIEW

**Comment by petercad** [comment]
@JoeOster @pmpeter1 could you review this PR when you have a chance? Thanks!

**Review by JoeOster — APPROVED** [review]
approving to launch ci

**Review by pmpeter1 — APPROVED** [review]
The goal is to have all oneMKL samples to have similar style.

**Comment by petercad** [comment]
Thanks, @JoeOster and @pmpeter1, for the reviews!

**Pull request merged**
