### PR TITLE
Dataset and Maintenance Changes for Classical ML Samples

### PR DESCRIPTION
**Pull request by raoberman**
# Existing Sample Changes
## Description

Updated the Following:
- Re-branding and instruction updates for READMEs and instructions within notebook several samples
- Renamed `IntelScikitLearn_Extensions_SVC_Adult` to `Intel_Extension_for_SKLearn_Performance_SVC_Adult`
- Added timer and visualizations for `Intel_Extension_for_SKLearn_Performance_SVC_Adult`
- Replaced `boston_dataset` with approved `fetch_california_housing` dataset for d4p samples

Fixes Issues:

- Boston Dataset
- Pickle concern
- setvars.sh --force concerns

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Command Line
- [ ] oneapi-cli
- [X] DevCloud
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by raoberman** [comment]
@praveenkk123 please approve again for CI

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Review by praveenkk123 — APPROVED** [review]

**Review by praveenkk123 — APPROVED** [review]

**Comment by praveenkk123** [comment]
@Rachel, Can I merge this PR?

**Comment by raoberman** [comment]
@praveenkk123  yes

**Pull request merged**
