### PR TITLE
fix issues : no crash for parsing a large log file and IPS#00555843

### PR DESCRIPTION
**Pull request by louie-tsai**
# Description

The change includes enablement for [the oneDNN tutorial](https://github.com/louie-tsai/oneAPI-samples/blob/master/Libraries/oneDNN/tutorials/tutorial_verbose_jitdump.ipynb) support a large oneDNN log file.
Without this change, the tutorial will crash when users input a large oneDNN log file.

This change also includes a fix for IPS#00555843. The issue only happens on DevCloud. Users wouldn't face any runtime issues on their local machine.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X ] Command Line

### CODE REVIEW

**Review by JoeOster — CHANGES_REQUESTED** [review]
Please update the description of the PR for future auditing purposes

**Comment by louie-tsai** [comment]
could you remind me what I should do for "Please update the description of the PR for future auditing purposes"?

**Review by JoeOster — DISMISSED** [review]

**Comment by louie-tsai** [comment]
json file is under below folder. 
https://github.com/oneapi-src/oneAPI-samples/blob/master/Libraries/oneDNN/tutorials/sample.json

anything missing?

**Review by JoeOster — APPROVED** [review]
approving for ci

**Review by JoeOster — DISMISSED** [review]
approving for ci

**Review by JoeOster — APPROVED** [review]
Seems ok to me

**Pull request merged**
