### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by bjodom**
# Existing Sample Changes
## Description

Fixed many typos and broken links in the Readme.md.

Fixes Issue# 

## External Dependencies

None

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Manually in the git IDE

### CODE REVIEW

**Comment by yuguen-intel** [comment]
No change can be made to the master branch, changing target branch to the development branch.

**Comment by yuguen-intel** [comment]
Your branch now needs to be updated to match the development branch (git merge development)

**Comment by jimmytwei** [comment]
@bjodom Is this different from #1699? I merged that one

**Comment by jimmytwei** [comment]
Closing this for now since it may be a duplicate for #1699

**Pull request closed without merging**
