### PR TITLE
Jacobi sample optimization

### PR DESCRIPTION
**Pull request by PradeepPotteti**
Signed-off-by: PradeepPotteti <potteti.pradeep@gmail.com>

# Existing Sample Changes
## Description

jacobi_iterative application (DenseLinearAlgebra) optimization

Fixes Issue# 

## External Dependencies

List any external dependencies created as a result of this change.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [X] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by krisrak** [comment]
@PradeepPotteti can u remove `using namespace sycl::ext::oneapi;` in jacobi.cpp, the devcloud and latest compiler, has moved atomics under sycl namespace, please  `using namespace sycl::ext::oneapi;` in this folder and also 3 other implementations and update this PR


`

**Review by krisrak — CHANGES_REQUESTED** [review]
remove `using namespace sycl::ext::oneapi;`, compiler has changed, no longer needed

**Review by krisrak — CHANGES_REQUESTED** [review]
change to `group_barrier(item_ct1.get_group());`

**Comment by krisrak** [comment]
@PradeepPotteti in kernel.cpp, there are 3 `item_ct1.barrier();`, replace with `group_barrier(item_ct1.get_group());`
In folder `sycl_migrated_optimized` and `sycl_migrated`

**Comment by PradeepPotteti** [comment]
Hi, 

We have included below suggested changes in "sycl_migrated" and "sycl_migrated_optimized" folders.
1) remove using namespace sycl::ext::oneapi
2) item_ct1.barrier();, replace with group_barrier(item_ct1.get_group());

Thanks,
Pradeep

**Review by krisrak — APPROVED** [review]
Verified changes

**Review by praveenkk123 — APPROVED** [review]

**Pull request merged**
