### PR TITLE
Revert "DEV1A-1215: fix include paths (#259)"

### PR DESCRIPTION
**Pull request by tony--**
# Description

This reverts commit a145f40ac146cdae396c233fdd0c9cd836049a1f.
According to DEV-1215, the change request was made in error and this change should be reverted.
FYI @anjgola @xmnboy 

Fixes DEV1A-1215

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Not tested.

### CODE REVIEW

**Comment by anjgola** [comment]
I am not sure this is correct, please sync with @akertesz for this. She should approve this review as FPGA expert for samples
An example : https://github.com/oneapi-src/oneAPI-samples/blob/214919acaf04a55297436e8d6d60adad7f2c6ce1/DirectProgramming/DPC%2B%2BFPGA/Tutorials/DesignPatterns/compute_units/src/pipe_array.hpp

**Comment by xmnboy** [comment]
Inspecting an October 6 beta10 Base Toolkit installation shows the following:

````
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail/esimd_host_util.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail/esimd_intrin.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail/esimd_math_intrin.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail/esimd_memory_intrin.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail/esimd_region.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail/esimd_types.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/detail/esimd_util.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/esimd.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/esimd_enum.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/esimd_math.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/esimd_memory.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd/esimd_view.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/atomic.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/atomic_accessor.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/atomic_enums.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/atomic_fence.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/atomic_ref.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/builtins.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/dot_product.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/esimd.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/fpga_device_selector.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/fpga_extensions.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/fpga_lsu.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/fpga_reg.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/fpga_utils.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/function_pointer.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/functional.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/group_algorithm.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/pipes.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/reduction.hpp
/opt/intel/oneapi/compiler/2021.1-beta10/linux/include/sycl/CL/sycl/intel/sub_group.hpp
````

Which indicates that the instructions we were originally provided are incorrect and the "intel" should be lowercase in the path, not uppercase. Can Audrey (@akertesz) or Swanpa (@srdontha) confirm? Or point us to someone in the know?

**Comment by akertesz** [comment]
Please make one more change:
```
#if defined(FPGA_EMULATOR)
  // DPC++ extension: FPGA emulator selector on systems without FPGA card
  INTEL::fpga_emulator_selector device_selector;
#else
  // DPC++ extension: FPGA selector on systems with FPGA card
  INTEL::fpga_selector device_selector;
#endif
```

**Comment by tony--** [comment]
I discussed this with @akertesz and they explained the change that is needed.  I will close this one and open a new PR which they will review.

**Pull request closed without merging**
