### PR TITLE
convolutionSeparable Migrating to SYCL

### PR DESCRIPTION
**Pull request by vidyalatha-badde**
# Adding a New Sample(s)
## Description

Migrating and optimizing the convolutionSeparable Application from CUDA to SYCL.

## Checklist
Administrative
- [X] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <Choudary, Chekuri; Krishnappa, Rakshith>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [X] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [X] Adhere to readme template 
- [X] Enforce format via clang-format config file
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [X] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [X] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [X] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [X] Tested using Dev Cloud when applicable

### CODE REVIEW

**Comment by jimmytwei** [comment]
Adding @jkinsky and @ishaghosh27 for README review.

**Comment by jimmytwei** [comment]
@vidyalatha-badde When I tried running the sample, I get:
```
make run_cpu
Scanning dependencies of target run_cpu
/bin/sh: 1: /oneAPI-samples/DirectProgramming/C++SYCL/guided_convolutionSeparable_SYCLmigration/build/bin/01_dpct_output: not found
make[3]: *** [01_dpct_output/CMakeFiles/run_cpu.dir/build.make:57: 01_dpct_output/CMakeFiles/run_cpu] Error 127
make[2]: *** [CMakeFiles/Makefile2:119: 01_dpct_output/CMakeFiles/run_cpu.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:126: 01_dpct_output/CMakeFiles/run_cpu.dir/rule] Error 2
make: *** [Makefile:118: run_cpu] Error 2
```

Please make sure that "make run_cpu", "make run_gpu", "make run_cmo_cpu" and "make run_cmo_gpu" work and fix any issues if necessary.

**Comment by vidyalatha-badde** [comment]
> @vidyalatha-badde When I tried running the sample, I get:
> 
> ```
> make run_cpu
> Scanning dependencies of target run_cpu
> /bin/sh: 1: /oneAPI-samples/DirectProgramming/C++SYCL/guided_convolutionSeparable_SYCLmigration/build/bin/01_dpct_output: not found
> make[3]: *** [01_dpct_output/CMakeFiles/run_cpu.dir/build.make:57: 01_dpct_output/CMakeFiles/run_cpu] Error 127
> make[2]: *** [CMakeFiles/Makefile2:119: 01_dpct_output/CMakeFiles/run_cpu.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:126: 01_dpct_output/CMakeFiles/run_cpu.dir/rule] Error 2
> make: *** [Makefile:118: run_cpu] Error 2
> ```
> 
> Please make sure that "make run_cpu", "make run_gpu", "make run_cmo_cpu" and "make run_cmo_gpu" work and fix any issues if necessary.
Ok, thanks for letting me know, I fixed the error (the errors are due to name changes in CMakeLists.txt files, anyways I corrected it) could you please give it a try and let me know if you still see the issue?

**Comment by jimmytwei** [comment]
@vidyalatha-badde The sample builds and runs now. 

The sample.json file is missing the expertise field. Adding @ishaghosh27 for feedback.

**Comment by ishaghosh27** [comment]
@vidyalatha-badde @jimmytwei please add Expertise: Code Optimization to the sample.json file.

**Comment by vidyalatha-badde** [comment]
> @vidyalatha-badde @jimmytwei please add Expertise: Code Optimization to the sample.json file.

Thanks, I've added it, could you please check it once?

**Review by IgorOchocki — APPROVED** [review]

**Comment by krisrak** [comment]
run_cpu and run_gpu both seem to run on CPU

**Pull request merged**
