### PR TITLE
Rendering toolkit oidn code sample PR

### PR DESCRIPTION
**Pull request by MichaelRoyceCarroll**
# Adding a New Sample(s)

## Description

New sample PR for oneapi rendering toolkit oidn sample. (library # 4 of 4)
See isseue: #697 

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see @JoeOster for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)
- [ ] Tested using Dev Cloud when applicable

### CODE REVIEW

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by MichaelRoyceCarroll** [comment]
This one I still need to fix... lost track of the toggle amongst other changes... WIP

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Review by pmpeter1 — APPROVED** [review]

**Comment by MichaelRoyceCarroll** [comment]
Hello... 0b20e73 'may' be a workaround for oidn dyld not loading issue. Can we launch it? Thanks.

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Review by praveenkk123 — APPROVED** [review]

**Pull request merged**
