### PR TITLE
Add the sorting implementation using a sycl buffer

### PR DESCRIPTION
**Pull request by zjin-lcf**
Please consider adding the SYCL impl. using buffers

### CODE REVIEW

**Comment by zjin-lcf** [comment]
It is helpful to have USM and buffer based implementations for each example.

**Comment by zjin-lcf** [comment]
> I think dpc_common.hpp should be last in the list and using "" not <>. It's not a system header-file, it's just a common header file shipped with our products.

Do I need to submit the file again or can you make the change ?

Thanks

**Comment by JoeOster** [comment]
@lqnguyen Please take a look at this

**Comment by lqnguyen** [comment]
The new source code looks fine, and I agree with @pmpeter1

**Comment by zjin-lcf** [comment]
> The new source code looks fine, and I agree with @pmpeter1

 Could you please modify your source code and my source code so that dpc_common.hpp should be last in the list ?

Thanks

**Comment by lqnguyen** [comment]
We will take your suggestion (about buffer-based implementation) to the code, and move "dpc_common.hpp" to the last in the list.

**Comment by zjin-lcf** [comment]
> After speaking with @lqnguyen I am not comfortable approving this at this time. He will be submitting a revised sample addressing concerns. Once that update occurs, this PR will be canceled and encourage @zjin-lcf to take a look at the new version of this sample at that time.

"you are not comfortable". Is it because the USM and buffer versions will be merged ? Please explain that.

**Comment by JoeOster** [comment]
We are making several additional changes beyond your suggestions into a single PR for the purpose of clarity

**Comment by zjin-lcf** [comment]
Okay.

**Pull request closed without merging**
