### PR TITLE
fix for cmake issue on 2021.2 release

### PR DESCRIPTION
**Pull request by louie-tsai**
# Description

Fixes # fixed PV reported issue for oneCCL on 2021.2

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X ] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [ ] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [ ] Implement coding guidelines and ensure code quality.
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [ ] Adhere to readme template 
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [ ] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

### CODE REVIEW

**Review by JoeOster — APPROVED** [review]

**Comment by JoeOster** [comment]
@louie-tsai - any ideas in regards to error messages?

**Review by JoeOster — CHANGES_REQUESTED** [review]
@louie-tsai Please take a look at the ci errors and get back to me in regards to your thoughts

**Comment by louie-tsai** [comment]
couldn't reproduce in PV's machine.


OS | Machine name | Login/password
-- | -- | --
Ubuntu 18.04 | nntcl38-qcht.inn.intel.com | root   spdlab

The built sample binaries are under ~/oneapi-samples/louie-tsai/oneAPI-samples/Libraries/oneCCL/oneCCL_Getting_Started/build folder.
image

**Review by JoeOster — APPROVED** [review]

**Comment by louie-tsai** [comment]
I tried again today.  the new changes still work fine on PV machine.
Could you double check in your env and merge the PR if possible?

**Pull request merged**
