### PR TITLE
Sim support memmory_attributes

### PR DESCRIPTION
**Pull request by artemrad**

### CODE REVIEW

**Comment by artemrad** [comment]
Test: 
Linux: https://psg-sc-arc.sc.intel.com/arc/dashboard/reports/show_job/648382217 
Windows:

**Comment by jimmytwei** [comment]
Added @yuguen-intel for general review and @ishaghosh27 to review the README.

**Comment by yuguen-intel** [comment]
This PR is still in the "draft" state, so I'll wait until @artemrad to ping me for reviewing

**Comment by yuguen-intel** [comment]
I've submitted this sim support as part of https://github.com/oneapi-src/oneAPI-samples/commit/f29e3c7ab6cc12c1c6af451812ad77fa008d1db7
I'm therefore closing this PR

**Pull request closed without merging**
