### PR TITLE
Rendering toolkit ospray code sample PR

### PR DESCRIPTION
**Pull request by MichaelRoyceCarroll**
# Adding a New Sample(s)

## Description

New sample PR for oneapi rendering toolkit ospray sample. (library # 1 of 4)
See issue: #697 

## Checklist
Administrative
- [ ] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager: @JoeOster

Code Development
- [ ] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [ ] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see @JoeOster for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)
- [ ] Tested using Dev Cloud when applicable

### CODE REVIEW

**Comment by JoeOster** [comment]
OSPDT Approved per OSPDT-1015 * All Apache Licensed libraries distributed as part of oneAPI have been approved
ospray is part of the oneAPI Rendering Toolkit

**Comment by MichaelRoyceCarroll** [comment]
This diff has the set-wise README.md included as well as the global GUID file updates.

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Review by pmpeter1 — APPROVED** [review]

**Comment by MichaelRoyceCarroll** [comment]
Added a fix for MacOS rkcommon error: https://github.com/oneapi-src/oneAPI-samples/pull/711#commitcomment-59104528

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by MichaelRoyceCarroll** [comment]
Progress here... I think I can make the same sample.json change that was just made for #712 to unblock Macos

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Pull request merged**
