### PR TITLE
Clang format check deleted due to moving to CI repo

### PR DESCRIPTION
**Pull request by andrey4latyshev**
Clang format check will be performed on the CI side, not in this repository

### CODE REVIEW

**Comment by anjgola** [comment]
Typically when a file is removed I expect to see a diff of the file being removed under 'Files Changed' tab. I think this is happening because your branch does not know that the file is added to master so it cannot detect that it is being deleted and there is nothing showing in the net delta of this commit. I think there is a chance that this commit sequence will not remove the file. 

To fix this, we first need to inform your branch that this file exists on master.. This can be done by first syncing your fork's master with the remote fork's master. Please use the section titled 'Sync fork and upstream repository
' at https://github.com/oneapi-src/oneAPI-samples/wiki/Git-Steps-for-Contribution to update your fork's master first. The PR should get automatically updated after that.

**Comment by andrey4latyshev** [comment]
> Typically when a file is removed I expect to see a diff of the file being removed under 'Files Changed' tab. I think this is happening because your branch does not know that the file is added to master so it cannot detect that it is being deleted and there is nothing showing in the net delta of this commit. I think there is a chance that this commit sequence will not remove the file.
> 
> To fix this, we first need to inform your branch that this file exists on master.. This can be done by first syncing your fork's master with the remote fork's master. Please use the section titled 'Sync fork and upstream repository
> ' at https://github.com/oneapi-src/oneAPI-samples/wiki/Git-Steps-for-Contribution to update your fork's master first. The PR should get automatically updated after that.

Thanks Anjali! Done.

**Comment by anjgola** [comment]
Still not seeing a delta. I am going to try and merge this and see if it actually removes the file.

**Comment by anjgola** [comment]
Nope, it doesn't work. Here is why : https://github.com/andrey4latyshev/oneAPI-samples/tree/clang-format-check. In this branch the script file is still there. You need to remove the file from there and create a PR again.

**Pull request merged**
