### PR TITLE
Moved model zoo sample to new directory

### PR DESCRIPTION
**Pull request by jitendra42**
# Description

Change Intel Model Zoo sample code directory. 

Fixes # (issue) 

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)
- [x] change directory structure of code sample

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [ ] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [ ] Implement coding guidelines and ensure code quality.
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [ ] Adhere to readme template 
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [ ] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

### CODE REVIEW

**Comment by JoeOster** [comment]
@jitendra42 - please take a look at your ci issues

**Comment by jitendra42** [comment]
@anjgola I just changed the directory of the sample and everything is same in this PR. The machine where CI test is running is missing `runipy`. Can you please take a look?

**Comment by anjgola** [comment]
@jitendra42  Apologies for the delay on this. I understand you only moved it but the error is happening, so we do need tor resolve it.
I ve sent this to CI team to add runipy.

**Comment by JoeOster** [comment]
Request for runipy to be installed on the test machine has been put in

**Comment by jitendra42** [comment]
@JoeOster All checks have passed, Can you please review the PR. Thanks.

**Review by JoeOster — APPROVED** [review]

**Pull request merged**
