### PR TITLE
removed dpc_common.hpp dependency, updated linux makefiles to remove …

### PR DESCRIPTION
**Pull request by Jenn500**
…'-r' in 'rm -rf'

Signed-off-by: Jenn500 <jennifer.l.jiang@intel.com>

### CODE REVIEW

**Comment by Jenn500** [comment]
please review @anjgola, Roman. previous was causing conflicts, it should be resolved .

**Comment by Jenn500** [comment]
I've tested on Linux PV machine, there is no issues. can I get more detail info about the failure on Linux? thanks!

**Comment by JoeOster** [comment]
@Jenn500 - The issue is with the clean section
rm: cannot remove 'vector-add-buffers_report.prj': Is a directory
make: *** [clean] Error 1

**Comment by Jenn500** [comment]
ouch. Thanks Joe. will fix it.

**Comment by Jenn500** [comment]
fixed the issue in makefiles. please review. @anjgola, roman, and joe.

**Comment by Jenn500** [comment]
updated .vcxproj with Joe's feedback on WindowsSDK too. please review @anjgola, Roman and Joe.

**Pull request merged**
