### PR TITLE
update Makefile for icpx compiler

### PR DESCRIPTION
**Pull request by rupakroyintel**
# Existing Sample Changes
## Updating the compiler to icpx as The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023.
Fixes Issue# 
Removes compiler deprecation warning messages during the building process
## Type of change
icpc to icpx transition

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by jimmytwei** [comment]
@rupakroyintel Can you update the PR to submit to the **development** branch? I

**Comment by rupakroyintel** [comment]
Thanks, @jimmytwei  for reviewing. I have updated the PR to submit to the development branch.

**Comment by jimmytwei** [comment]
@rupakroyintel Can you create a new branch from your fork that is based off of the current development branch? The master branch contains some changes that we'll plan to merge when the next base kit version is released. You can close this PR and create a new one. Sorry for the inconvenience.

**Comment by rupakroyintel** [comment]
Here is the updated pull request: https://github.com/oneapi-src/oneAPI-samples/pull/1363. Closing this PR. Thanks.

**Pull request closed without merging**
