### PR TITLE
HSOptical sample

### PR DESCRIPTION
**Pull request by ShwethaSelma**
# Existing Sample Changes
## Description

Fix for error on PVC machine, CMakefile change and README update.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [X] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by krisrak** [comment]
.ipynb_checkpoint has to be removed

**Comment by ShwethaSelma** [comment]
> .ipynb_checkpoint has to be removed

deleted .ipynb_checkpoints from folders.

**Comment by krisrak** [comment]
can be merged

**Comment by jimmytwei** [comment]
@jkinsky Can you review the README? Once I get your approval, I will merge.

**Pull request merged**
