### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rskasturi**
# Existing Sample Changes
## Description
Single file execution for FPGA on Intel Devcloud for oneAPI

### CODE REVIEW

**Comment by yuguen-intel** [comment]
These instructions are already appearing in the FPGA top level readme: 
https://github.com/oneapi-src/oneAPI-samples/tree/master/DirectProgramming/C%2B%2BSYCL_FPGA#build-and-run-the-samples-on-intel-devcloud-optional

**Comment by rskasturi** [comment]
Hi, the instructions are more generic on reference for FPGA. User's need to activate oneAPI environment on Devcloud before execution and that is missing in README.

**Comment by rskasturi** [comment]
Okay Thanks, contributed as it shall be helpful for user's to have dedicated instructions for oneAPI devcloud.

**Comment by yuguen-intel** [comment]
We used to have these instructions but decided to remove them as:
- having long readmes with instructions for all different environments was obfuscating the actual simple build commands
- devcloud has its own documentation, which change with time
- we can't document all possible environments 

I hope this clarifies :)

**Pull request closed without merging**
