### PR TITLE
Add links to Cookbook recipes for oneMKL Samples

### PR DESCRIPTION
**Pull request by andreyfe1**
# Existing Sample Changes
## Description

It's useful to link oneMKL Samples with [oneMKL cookbook recipes](https://www.intel.com/content/www/us/en/docs/onemkl/cookbook/current/overview.html). Following samples have been changed:
* Black-Scholes
* Block Cholesky Decomposition
* Block LU Decomposition
* Computed Tomography Reconstruction
* Monte Carlo European Options

## External Dependencies

List any external dependencies created as a result of this change:
* Links to https://www.intel.com/content/www/us/en/docs/onemkl/cookbook/current/overview.html

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

N/A

### CODE REVIEW

**Review by sknepper — COMMENTED** [review]
Thanks for making the changes, Andrey! To keep the links aligned with the latest Cookbook documentation, I think the "2024-0" string can be replaced with "current", and it will automatically redirect to the latest version.

E.g., https://www.intel.com/content/www/us/en/docs/onemkl/cookbook/current/slv-sys-lin-eq-lu-factor-blk-tridiag-coeff-mat.html

**Comment by andreyfe1** [comment]
@sknepper, great idea, thanks. I've made necessary changes

**Review by sknepper — APPROVED** [review]
This is great, thanks Andrey!
I verified each of the 5 links works as expected.

**Comment by andreyfe1** [comment]
Hi @tomlenth, @jimmytwei. Could you please merge if everything is fine?

**Pull request merged**
