### PR TITLE
Added the common includes directory to VS project file in Particle Diffusion sample

### PR DESCRIPTION
**Pull request by Alberto-Villarreal**

### CODE REVIEW

**Comment by Alberto-Villarreal** [comment]
@anjgola ,@JoeOster , Roman, Could you please approve to trigger ci tests, thanks

**Comment by Alberto-Villarreal** [comment]
@mkitez  Thanks

**Comment by JoeOster** [comment]
@Alberto-Villarreal - please take a look and resolve your conflict please.

**Comment by Alberto-Villarreal** [comment]
@anjgola I'm not able to resolve the conflicts. The "Resolve conflict" button shows grayed out. Any suggestions for this? Thanks.

**Pull request merged**
