### PR TITLE
Remove beta compatibility code from oneMKL samples

### PR DESCRIPTION
**Pull request by petercad**
# Description

This PR removes old code that was used to support a previous oneMKL beta, prior to oneAPI header restructuring.

# How Has This Been Tested?

- [X] Command Line

### CODE REVIEW

**Comment by petercad** [comment]
@JoeOster would you be able to take a look at this PR?

**Review by JoeOster — APPROVED** [review]
approved for ci to run

**Comment by JoeOster** [comment]
@anjgola - can you look at this please. It doesn't seem as ci has run on this sample

**Comment by anjgola** [comment]
Sorry for the delay, results should be up soon.

**Comment by petercad** [comment]
@anjgola It looks like something went wrong in the Windows CI infrastructure... the log for `monte_carlo_european_opt` builds `monte_carlo_european_opt` but then runs `monte_carlo_pi`, while `monte_carlo_pi` cannot find the compiled binaries (though compilation is successful). It looks like CI is trying to make the samples in parallel in the same directory (note that this MR doesn't change any makefiles).

Can you re-run Windows CI to see if it's reproducible?

**Comment by anjgola** [comment]
Acknowledging that I read your comment, I am finding out what is going in CI but having some access/role clarity problems so it might be longer than usual.

**Comment by sknepper** [comment]
Is it possible to please re-run the Windows validation for this pull request and #409?  Thanks!

**Review by JoeOster — DISMISSED** [review]
The json file needs to have the paths updated from the look of things

**Comment by petercad** [comment]
> The json file needs to have the paths updated from the look of things

Which paths are you referring to? Also, is this for specific .json files or all of the oneMKL files?

**Comment by JoeOster** [comment]
> > The json file needs to have the paths updated from the look of things
> 
> Which paths are you referring to? Also, is this for specific .json files or all of the oneMKL files?

ci output for windows, it is not liking some paths, for example here are some of them

Could Not Find C:\BuildAgent\work\27f863ad4717898f\sample-tester\test-resources\random_sampling_without_replacement\lottery.exe

Could Not Find C:\BuildAgent\work\27f863ad4717898f\sample-tester\test-resources\random_sampling_without_replacement\lottery.exp

Could Not Find C:\BuildAgent\work\27f863ad4717898f\sample-tester\test-resources\random_sampling_without_replacement\lottery.lib

**Comment by petercad** [comment]
@JoeOster thanks for the clarification. Those paths come from the CI system; the makefile builds everything in the current directory. The errors you mention appear to be coming from CI mistakenly trying to parallel build several samples concurrently in the same folder, and the makefiles are overwriting each other.

Note that this PR doesn't change any makefiles/json.

**Review by JoeOster — APPROVED** [review]
When I run the ci manually and compared to the older automated fashion there errors are different, rerunning to show current errors

**Comment by JoeOster** [comment]
seems to build fine, just when ci is running stuff, its reading/writing to same folder in parallel and stepping on itself.

**Pull request merged**
