### PR TITLE
Add W/A to README of histogram sample to avoid some issues on GPU

### PR DESCRIPTION
**Pull request by dsobolev-dev**
Add W/A to README of histogram sample to avoid some issues on GPU

Signed-off-by: Sobolev, Dmitriy <dmitriy.sobolev@intel.com>

# Description

The W/A has been added to be able to run the sample on GPU with L0 using oneAPI beta09.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Must be tested via the CI pipeline as the only possible breaking changes were to README.md file

### CODE REVIEW

**Comment by capatober** [comment]
Do not forget to remove it from the Readme when the issue is disappeared

**Review by capatober — APPROVED** [review]

**Review by JoeOster — APPROVED** [review]

**Comment by JoeOster** [comment]
@capatober - please take a look at your scripts as Linux failed to build

**Comment by capatober** [comment]
@JoeOster, I'm not familiar with this sample.
@JhaShweta1, since you are the author of this code could you please make changes in scripts according to the Readme?

**Comment by anjgola** [comment]
Merging workaround.

**Pull request merged**
