### PR TITLE
fix cmake error for windows with dpcpp and remove Visaul Stuido IDE support

### PR DESCRIPTION
**Pull request by louie-tsai**
…upport

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue) 

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X ] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X ] Command Line

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files.

### CODE REVIEW

**Review by JoeOster — DISMISSED** [review]
approve for ci

**Comment by louie-tsai** [comment]
fix a cmakefile issue. please try CI testing one more time.

**Review by JoeOster — DISMISSED** [review]
approve for ci

**Review by JoeOster — APPROVED** [review]
approving for ci

**Comment by louie-tsai** [comment]
The compiler still look for Microsoft VC instead of Clang. The issue doesn't happen in PV machine.
```
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is Clang 12.0.0 with GNU-like command-line
```

I set the compiler manually in samples.json file.
if it still fail, we should check CI machine env.

here is the validation from PV machine.
image

**Pull request merged**
