### PR TITLE
Monte Carlo Multi GPU sample readme update

### PR DESCRIPTION
**Pull request by jkinsky**
# Existing Sample Changes
## Description

Corrected some structure issues (compared to new template). Corrected some formatting issues. Updated sample.json file to include the same name as the readme.md file. Corrected some grammar and punctuation issues. Corrected spacing issues. Updated build instructions with information to change to the proper directory to run the apps.

Fixes Issue# 

## External Dependencies

N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Documentation

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [x] VSCode

### CODE REVIEW

**Comment by jkinsky** [comment]
Adding @jimmytwei for notices.

**Review by tomlenth — CHANGES_REQUESTED** [review]
@praveenkk123,  since Rakshith is out, can you address these issues? 

The readme looks fine to me.  As for the json: 
•	Expertise should be as follows
 "expertise": "Code Optimization"
•	The description could be more, uhm, descriptive.  Thoughts? 
o	Current: Evaluates fair call price for a given set of European Options using the MonteCarlo approach
o	Recommend: Migrated from CUDA to SYCL and optimized for multi GPU, sample valuates fair call price for a given set of European Options using the MonteCarlo approach

**Comment by jimmytwei** [comment]
@tomlenth @praveenkk123 @jkinsky I'm fine with expertise to be "Code Optimization" and the description to be
"Migrated from CUDA to SYCL and optimized for multi GPU, sample evaluates fair call price for a given set of European Options using the Monte Carlo approach" 

@jkinsky Can you update these changes in your PR? 
@praveenkk123 Can you let us know if this is fine? Otherwise, I'll approve and merge by EOW

**Comment by jkinsky** [comment]
Amended the commit with the changes requested to the sample.json file.

**Comment by jimmytwei** [comment]
@jkinsky Looks like there are some conflicts. I was getting a request to merge PR #1709. Can you resync your local branch with the upstream development branch?

**Comment by jkinsky** [comment]
Closing this PR. Will resubmit with changes once the other changes are merged.

**Pull request closed without merging**
