### PR TITLE
IRTK_Learning_Path: --force in all sh's, new run_CPU_CI.sh and run_GPU_CI.sh, new guids

### PR DESCRIPTION
**Pull request by robmariv**
# Existing Sample Changes
## Description

Add of IRTK_Learning_Path inside of oneAPI-samples/RenderingToolkit/
--force in all sh's.
new run_CPU_CI.sh and run_GPU_CI.sh for 4.1_OpenVKL_Intro_CPU_GPU and its sample.json file updated.
new guids.

Fixes Issue# 

## External Dependencies

List any external dependencies created as a result of this change.
None

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by MichaelRCarroll-Intel** [comment]
@robmariv: If you want/need to see the cherry-pick and chmod script fix, refer to my release/2024.1 PR commit here: https://github.com/oneapi-src/oneAPI-samples/pull/2255/commits/a397af51922f243acec98b4dd87a65d129079a7b

**Comment by MichaelRCarroll-Intel** [comment]
Fixed script perms... but something is funny with git bash... script perms come down in git bash as 755. On my linux machine they come down as 644... then I'm able to change perms. Create the commit and auto merge to the branch here... git bash is auto configured with scripts on windows and linux, maybe they are different?

**Comment by MichaelRCarroll-Intel** [comment]
@jimmytwei : It looks like we are done here, any blocks to approve?

**Comment by MichaelRCarroll-Intel** [comment]
I think this is the culprit: https://unix.stackexchange.com/questions/621738/git-checkout-file-changes-permissions-for-existing-file

**Comment by jimmytwei** [comment]
@robmariv @MichaelRCarroll-Intel We're good. If you want me to approve and merge let me know.

**Comment by robmariv** [comment]
@jimmytwei, I have no blocks.  I am good with approving and merging.

**Pull request merged**
