### PR TITLE
New AI Sample for Optimize PyTorch Models using Intel® Extension for PyTorch* (IPEX)

### PR DESCRIPTION
**Pull request by louie-tsai**
# Adding a New Sample(s)

## Description

This notebook guides you through the process of extending your PyTorch code with Intel® Extension for PyTorch* (IPEX) with optimizations to achieve performance boosts on Intel® hardware.

## Checklist
Administrative
- [x] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <insert Name Here>
- [x] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [ ] Enforce format via clang-format config file
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [x] OSPDT Approval (see Project Manager for assistance)
- [ ] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [x] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [ ] Tested using Dev Cloud when applicable

### CODE REVIEW

**Comment by louie-tsai** [comment]
Still WIP
Added @devpramod-intel as the sample author

**Comment by jimmytwei** [comment]
Added @ishaghosh27 to review the READMEs.

**Review by ishaghosh27 — DISMISSED** [review]

**Comment by louie-tsai** [comment]
@devpramod-intel
Could you attached the notebooks result by following the sample.json command?

**Comment by louie-tsai** [comment]
@jimmytwei
Any CI/CD issue/AR for this PR?

**Comment by ishaghosh27** [comment]
@jimmytwei I am not added as the reviewer for this. Please add me so I can review.

**Review by ishaghosh27 — APPROVED** [review]

**Comment by jimmytwei** [comment]
@louie-tsai Is the removal of [DirectProgramming/DPC++/StructuredGrids/1d_HeatTransfer/src/1d_HeatTransfer.cpp] accidental?

**Review by jimmytwei — APPROVED** [review]

**Comment by jimmytwei** [comment]
Changes merged in PR #1243 so closing this PR out.

**Pull request closed without merging**
