### PR TITLE
Correct modin samples

### PR DESCRIPTION
**Pull request by amyskov**
# Existing Sample Changes
## Description

This PR corrects Modin related samples. Changes are next:
1) Change config setting technique for more appropriate for python file.
2) Specify config settings for newer Modin versions (since 0.12.0 version config for OmniSci enabling was changed).
3) Remove `compression` parameter from `read_csv` function (csv file compression is inferred automatically and explicit notion of `compression` parameter causes "default-to-pandas" behavior and performance degradation).
4) Remove `nrows` parameter from `read_csv` function to avoid "default-to-pandas" behavior (`nrows` parameter is not supported yet in Modin with OmniSci backend).
5) `DataFrame.query` function calls replaced with equivalents to avoid "default-to-pandas" behavior and avoid performance degradation (`DataFrame.query` is not supported yet in Modin with OmniSci backend).
6) Alternative installation guidance was fixed, `sample.json` file was set similarly to https://github.com/oneapi-src/oneAPI-samples/pull/863 change.
7) Warnings were disabled to avoid unneeded output cluttering.
8) Fixed minor typos.

## External Dependencies

List any external dependencies created as a result of this change.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by amyskov** [comment]
Hi @JoeOster ! Could you take a look on this and on the https://github.com/oneapi-src/oneAPI-samples/pull/769 PRs?

**Comment by praveenkk123** [comment]
Please submit to development branch but not the master branch

**Comment by amyskov** [comment]
> Please submit to development branch but not the master branch

@praveenkk123 target branch was changed.

**Review by praveenkk123 — DISMISSED** [review]
Approve for CI

**Review by raoberman — CHANGES_REQUESTED** [review]
@amyskov can you also ensure that the conda install commands are correct for the README of the sample? `conda install modin` should be good i believe . 

https://github.com/oneapi-src/oneAPI-samples/blob/master/AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md

**Comment by raoberman** [comment]
@louie-tsai  @praveenkk123  please approve for 2022.1 since the change for census is important (after README edit i requested as conda install command currently listed is not latest)

**Comment by amyskov** [comment]
> @amyskov can you also ensure that the conda install commands are correct for the README of the sample? `conda install modin` should be good i believe .
> 
> https://github.com/oneapi-src/oneAPI-samples/blob/master/AI-and-Analytics/Getting-Started-Samples/IntelModin_GettingStarted/README.md

@raoberman verified `conda install` command was added.

**Comment by amyskov** [comment]
Additional changes:
- `nrows` parameter was removed from `read_csv` function to avoid "default-to-pandas" behavior (`nrows` parameter is not supported yet in Modin with OmniSci backend).
- Warnings were disabled to avoid unneeded output cluttering.

**Comment by raoberman** [comment]
@amyskov please re-submit this PR to the master branch. See Praveen and I's email for info

**Comment by amyskov** [comment]
> @amyskov please re-submit this PR to the master branch. See Praveen and I's email for info

@raoberman PR was re-summited and rebased.

**Review by praveenkk123 — DISMISSED** [review]
Approve for CI

**Comment by amyskov** [comment]
Modin configurations were changed to avoid triggering https://github.com/modin-project/modin/issues/4017 issue. Also installation instructions were slightly modified to speed-up packages installation.

**Review by praveenkk123 — APPROVED** [review]

**Comment by amyskov** [comment]
Hi @praveenkk123!
For some reason `Samples validation (Linux)` test failed with strange output, while if i run `steps` commands from `sample.json` file tests passes (as i understood this file contains CI settings). Can you please provide me with instructions to reproduce CI fail? Or maybe you can give me some suggestions how i can tune CI to pass tests?

**Comment by dchigarev** [comment]
@amyskov please rebase on the current master, we recently merged #863 that should fix CI testing

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by amyskov** [comment]
@praveenkk123 Census sample CI config was changed as well, but `jupyter nbconvert` was used instead of `runipy` because of hardcoded timeout value in `runipy` (see https://github.com/jupyter/jupyter_client/issues/197 for details), that raised error during long IO step execution. Can you, please, restart the CI?

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by amyskov** [comment]
@praveenkk123 merge conflict was fixed, could you please restart the CI?

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by praveenkk123** [comment]
All tests passed. Can I merge this?

**Comment by amyskov** [comment]
> All tests passed. Can I merge this?

Yes, sure.

**Pull request merged**
