### PR TITLE
Creating a FPGA Printf tutorial

### PR DESCRIPTION
**Pull request by zibaiwan**
## Description

Creating a tutorial for SYCL printf. This tutorial demonstrates how to use printf in a DPC++ FPGA program.

## Checklist
Administrative
- [x] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): @mdbtucker 

Code Development
- [x] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [x] Adhere to readme template 
- [x] Enforce format via clang-format config file
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [x] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see @JoeOster for assistance)
- [x] Compile using the following compiler flags and fix any warnings, the flags are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Virus scan

Review
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth(@tomlenth) and/or Joe Oster(@JoeOster)

### CODE REVIEW

**Review by mdbtucker — APPROVED** [review]
Already reviewed in detail on Zibai's fork

**Review by pmpeter1 — APPROVED** [review]

**Review by tomlenth — CHANGES_REQUESTED** [review]
In the Key Concepts section, the "Advantages" link points to the motivation section at the top of the readme and "Limitations" points to the Limitations section.  This is a bit confusing; bouncing the user back up to something they presumably read is disorienting esp since the section is not explicitly "Advantages".  Would be best to simply provide a short bullet list of advantages (this is a key concept section) and maybe include the link to limitations. 

In teh Examining the reports sections, there's an explanation on where to find the report.  Can you include even just a one sentence second paragraph that notes what to look for and find in the report.

**Comment by zibaiwan** [comment]
Committed the changes suggested by @tomlenth.

**Review by tomlenth — APPROVED** [review]
thanks for the updates!

**Comment by JoeOster** [comment]
Please cancel and make a new PR targeting the "Development" branch

**Comment by mdbtucker** [comment]
> > Please cancel and make a new PR targeting the "Development" branch
> 
> Hi Joe,
> 
> Can I just edit this existing PR and change the target branch to "Development" instead?
> 
> Thanks,
> 
> Zibai

Yes, that will be fine.  You'll have to wait until the Development branch is created, which I believe will not happen until after 2021.4 is released.

**Pull request closed without merging**
