### PR TITLE
FPGA: Fix namespace of deivce_ptr and host_ptr

### PR DESCRIPTION
**Pull request by steffenlarsen**
# Existing Sample Changes
## Description

The device_ptr and host_ptr aliases in DPC++ is from the [sycl_ext_intel_usm_address_spaces](sycl/doc/extensions/supported/sycl_ext_intel_usm_address_spaces.asciidoc) and as such is under the sycl::ext::intel namespace, rather than the sycl namespace. This commit fixes the namespaces of all uses of these aliases.

Replaces https://github.com/oneapi-src/oneAPI-samples/pull/2288.

## External Dependencies

None.

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Following the build instructions in each of the respective sample directories.

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by yuguen-intel** [comment]
What version of the compiler are you using to test this?
Internal regression tests are passing with 2024.2

**Comment by steffenlarsen** [comment]
This is to adjust for upcoming releases, including current https://github.com/intel/llvm. Note that `sycl::device_ptr` and `sycl::host_ptr` were deprecated in 2024.2.

**Comment by yuguen-intel** [comment]
Ok - thanks I'll keep your PR opened for now until the FPGA compiler integrates this upstream change - I'll merge your PR then

**Comment by yuguen-intel** [comment]
Some have been addressed (but not all) I'm still keeping this PR opened as I don't have a way to test it now, and we are close to the 2024.2 release.
This will get merged in the 2025.0 release

**Comment by yuguen-intel** [comment]
All of these should have been addressed now through other PRs that we were able to validate along then way. Closing.

**Pull request closed without merging**
