### PR TITLE
QuasirandomGenerator Migrating to SYCL

### PR DESCRIPTION
**Pull request by ManjulaChalla**
# Adding a New Sample(s)
## Description

Migrating and optimizing the quasirandomGenerator  Application from CUDA to SYCL.

## Checklist
Administrative
- [X] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): <Choudary, Chekuri; Krishnappa, Rakshith>
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [X] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [X] Adhere to readme template 
- [X] Enforce format via clang-format config file
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [X] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [X] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [X] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [X] Tested using Dev Cloud when applicable

### CODE REVIEW

**Comment by jimmytwei** [comment]
Adding @jkinsky and @ishaghosh27 for README review.

**Review by jkinsky — APPROVED** [review]

**Comment by jimmytwei** [comment]
@ManjulaChalla When I run make run_cpu, I get this error message:
```
dpct_output Starting...

Allocating GPU memory...
Allocating CPU memory...
Initializing QRNG tables...

Testing QRNG...

quasirandomGenerator, Throughput = 0.5351 GNumbers/s, Time = 0.00392 s, Size = 2097152 Numbers, NumDevsUsed = 1, Workgroup = 256

Reading GPU results...
Comparing to the CPU results...

L1 norm: 7.275965E-12

Testing inverseCNDgpu()...

quasirandomGenerator-inverse, Throughput = 1.3131 GNumbers/s, Time = 0.00160 s, Size = 2097152 Numbers, NumDevsUsed = 1, Workgroup = 128
Reading GPU results...

Comparing to the CPU results...
L1 norm: 3.656201E-06

Shutting down...
make[3]: *** [01_dpct_output/CMakeFiles/run_cpu.dir/build.make:57: 01_dpct_output/CMakeFiles/run_cpu] Error 1
make[2]: *** [CMakeFiles/Makefile2:146: 01_dpct_output/CMakeFiles/run_cpu.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:153: 01_dpct_output/CMakeFiles/run_cpu.dir/rule] Error 2
make: *** [Makefile:131: run_cpu] Error 2
```

Please verify that make run_cpu and make run_gpu doesn't return an error.

**Comment by ManjulaChalla** [comment]
> @ManjulaChalla When I run make run_cpu, I get this error message:
> 
> ```
> dpct_output Starting...
> 
> Allocating GPU memory...
> Allocating CPU memory...
> Initializing QRNG tables...
> 
> Testing QRNG...
> 
> quasirandomGenerator, Throughput = 0.5351 GNumbers/s, Time = 0.00392 s, Size = 2097152 Numbers, NumDevsUsed = 1, Workgroup = 256
> 
> Reading GPU results...
> Comparing to the CPU results...
> 
> L1 norm: 7.275965E-12
> 
> Testing inverseCNDgpu()...
> 
> quasirandomGenerator-inverse, Throughput = 1.3131 GNumbers/s, Time = 0.00160 s, Size = 2097152 Numbers, NumDevsUsed = 1, Workgroup = 128
> Reading GPU results...
> 
> Comparing to the CPU results...
> L1 norm: 3.656201E-06
> 
> Shutting down...
> make[3]: *** [01_dpct_output/CMakeFiles/run_cpu.dir/build.make:57: 01_dpct_output/CMakeFiles/run_cpu] Error 1
> make[2]: *** [CMakeFiles/Makefile2:146: 01_dpct_output/CMakeFiles/run_cpu.dir/all] Error 2
> make[1]: *** [CMakeFiles/Makefile2:153: 01_dpct_output/CMakeFiles/run_cpu.dir/rule] Error 2
> make: *** [Makefile:131: run_cpu] Error 2
> ```
> 
> Please verify that make run_cpu and make run_gpu doesn't return an error.

Hi @jimmytwei,

I have updated the CMakeFile and verified running the code on CPU and GPU. Let me know if the issue still exists.

**Comment by jimmytwei** [comment]
@ManjulaChalla I'm still getting the same output. The sample seems to run but make is displaying an error at the end.

**Comment by jimmytwei** [comment]
@ManjulaChalla The sample.json file is missing the expertise field. Adding @ishaghosh27 for feedback.

**Comment by ishaghosh27** [comment]
@ManjulaChalla @jimmytwei Please add Expertise: Code Optimization to the sample.json file

**Pull request merged**
