### PR TITLE
Create a shared include directory for FPGA code samples

### PR DESCRIPTION
**Pull request by ByrSinc**
## Description

This change creates an include directory for re-usable shared header libraries in DPC++ FPGA designs. The initial header added to this directory as part of this change is pipe_utils.hpp, which consolidates the pipe_array.hpp, pipe_array_internal.hpp and PipeDuplicator.hpp from various code samples into one shared header.

## External Dependencies

N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Review by JoeOster — APPROVED** [review]
approve for ci only

**Comment by JoeOster** [comment]
@mdbtucker SOmeone will need to confirm that this works with the aggragator before we merge

**Comment by mdbtucker** [comment]
> @mdbtucker SOmeone will need to confirm that this works with the aggragator before we merge

CI for this directory structure was tested in https://github.com/oneapi-src/oneAPI-samples/pull/475

**Review by mdbtucker — DISMISSED** [review]
Approving to run CI

**Review by mdbtucker — APPROVED** [review]

**Review by pmpeter1 — APPROVED** [review]
The code does a good job at following code style guidelines.

**Comment by JoeOster** [comment]
Please cancel and make a new PR targeting the "Development" branch

**Comment by ByrSinc** [comment]
I've moved this PR to the development branch here:
https://github.com/oneapi-src/oneAPI-samples/pull/680

**Pull request closed without merging**
