### PR TITLE
Updated README - added dpcpp for windows support

### PR DESCRIPTION
**Pull request by yehudaorel**
# Existing Sample Changes
## Description

Verified that DPCPP compiler works on windows (CMake v3.21+), and updated the getting_started sample readme to include instructions for dpcpp build.

## External Dependencies
N/A

## Type of change

- [ X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Used oneDNN instructions to build and compile using DPC++ on windows, works for CMake versions 3.21 and above.

- [X] Command Line
- [ ] oneapi-cli
- [X] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Review by louie-tsai — APPROVED** [review]
looks good to me.

**Comment by louie-tsai** [comment]
@yinghu5 
could you help to review the PR?

**Comment by yinghu5** [comment]
looks fine to me too.

**Review by yinghu5 — APPROVED** [review]
look good to me

**Review by louie-tsai — APPROVED** [review]

**Comment by louie-tsai** [comment]
@jimmytwei 
Could you help us to merge the PR? thanks

**Comment by jimmytwei** [comment]
Adding @ishaghosh27 for reviewing README

**Review by ishaghosh27 — APPROVED** [review]

**Pull request merged**
