### PR TITLE
OpenMP Offload C++ Tutorials readme update

### PR DESCRIPTION
**Pull request by jkinsky**
# Existing Sample Changes
## Description

Restructured to match new template—more or less. Change readme name to match the name of the sample found in the sample.json file. Added category to readme (as indicated in the sample.json file). Corrected some formatting. Updated some branding.

Fixes Issue# 

## External Dependencies

N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Documentation quality

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] VSCode

### CODE REVIEW

**Comment by jkinsky** [comment]
Adding @jimmytwei for notices

**Comment by jkinsky** [comment]
Adding @karlqi2000 for review.

**Review by tomlenth — APPROVED** [review]
This looks fine, but I did not validate the steps.  Any insight on whether CI can do anything with this for testing?

**Comment by jimmytwei** [comment]
@tomlenth The CI will build and run the sample based off of the sample.json file. It won't parse the READMEs.
I can kick off the CI to see if the sample builds successfully based on the steps outlined in the sample.json file.

**Comment by jkinsky** [comment]
The build and execution commands in the sample.json result in output, so CI will be successful. Unfortunately, that doesn't mean the notebooks work or that they are full of issues. That's the primary interface for the sample.

**Comment by tomlenth** [comment]
@jimmytwei  @jkinsky  So, although the "samples' build and run, there's no content quality check, just like a readme may be inaccurate and out of synch with the json.  my hope was at least the CI could execute each cell, but that still doesn't mean the content is correct.  This seems like a much bigger issue.  step 1, make sure it's functionally correct, step 2, figure out how to do content reviews on training, juypter AI based, samples and any other notebooks.  I wouldn't hold up this one sample for that larger problem.

**Pull request merged**
