### PR TITLE
samples.json fix

### PR DESCRIPTION
**Pull request by jedxops**
# Description

Recategorizes samples structure in IDE/oneapi-cli by updating the samples.json file for each code sample

Fixes # (issue)  N/A

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] oneapi-cli

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [X] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [X] Implement coding guidelines and ensure code quality.
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [X] Adhere to readme template 
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [X] Enforce format via clang-format config file
- [X] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [X] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [X] Tested using Dev Cloud when applicable
- [X] Implement fixes for ONSAM Jiras
- [X] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

### CODE REVIEW

**Review by JoeOster — DISMISSED** [review]

**Comment by anjgola** [comment]
It is always recommended to do shorter commits so that reviewers can pay attention to details and any failures can be isolated and spotted more easily.
The merge conflicts need to be resolved in your branch like this : https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line.
The resolutions will be recorded by git and should reflect int he PR.

**Comment by anjgola** [comment]
Are the changes from Intel oneAPI Tools to oneAPI Tools...brand approved?

Are the changes to the categories reflected in schema changes in the aggregator? Can you provide link of that PR please.

**Comment by anjgola** [comment]
Requesting review from Paul for IDE fields and Tom for aggregator category schema.

**Comment by xmnboy** [comment]
By "IDE fields" review, I believe @anjgola meant the `sample.json` fields. There are way too many commits to review all of them. I went through and reviewed a [not very random] sampling of the changes and every one that I checked (~20) looked good and consistent with the original request. So I'm going to mark with a 👍

**Review by xmnboy — APPROVED** [review]
By "IDE fields" review, I believe @anjgola meant the `sample.json` fields. There are way too many commits to review all of them. I went through and reviewed a [not very random] sampling of the changes and every one that I checked (~20) looked good and consistent with the original request. So I'm going to mark with a 👍

**Review by JoeOster — APPROVED** [review]

**Comment by jedxops** [comment]
Completely agree with you Anjali.

The original request (from people much higher than me on the totem pole) was simply to update all the .json files (117 of them, I believe) to reflect new oneapi-cli structural changes per decisions made by the oneapi samples committee. I was not instructed to merge on the intel official repo every 10 files updated, or anything like that, although, looking back on it, merging 20-30 files at a time probably would have been a lot safer and smoother. 20-30 files at a time is a reasonable amount of files to check for one person, especially since we are only talking 3-4 lines per file changed.

**Comment by jedxops** [comment]
Anjali, do you still need this answered? "Are the changes from Intel oneAPI Tools to oneAPI Tools...brand approved?
Are the changes to the categories reflected in schema changes in the aggregator? Can you provide link of that PR please."

**Comment by anjgola** [comment]
Thanks Jeff. The PR is merged so no more questions, if the schema fails there will be failures in the pipeline.

**Comment by anjgola** [comment]
It is failing :-/. Sending email.

**Comment by jedxops** [comment]
Thanks to Thomas Ingleby, Tom Lenth, and Anjali Gola -the schema is no longer failing and there is no more action required on this PR. -Merged

**Pull request merged**
