### PR TITLE
Provide oneVPL samples for 2021.1-beta09

### PR DESCRIPTION
**Pull request by mav-intel**
Signed-off-by: Marc A. Valle <marc.a.valle@intel.com>

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [ ] oneapi-cli
- [x] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [x] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [x] Implement coding guidelines and ensure code quality.
- [x] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [x] Adhere to readme template 
- [x] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Enforce format via clang-format config file
- [x] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [x] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [x] Implement fixes for ONSAM Jiras

### CODE REVIEW

**Comment by JoeOster** [comment]
@mav-intel - Please provide a status update on this Pull request

**Comment by mav-intel** [comment]
@JoeOster This pull request will  not move forward until beta09 is available to test against in CI, as it relies on header updates in beta09

**Comment by krisdale** [comment]
@mav-intel Can we move this PR forward now that beta09 is available?

**Review by anjgola — APPROVED** [review]
Approving.

**Comment by anjgola** [comment]
Merging as requested by @srdontha.

**Pull request merged**
