### PR TITLE
Update the use_library test to remove the HLS and OCL flows 

### PR DESCRIPTION
**Pull request by ajaykumarkannan**
Update the use_library test to remove the HLS and OCL flows since they are no longer supported in the emulation flows.

# Existing Sample Changes
## Description
Remove the HLS and OCL flows

Fixes Issue# 

## External Dependencies

n/a

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by tyoungsc** [comment]
LGTM. @JoeOster sorry to ask again, but could you approve/merge this for me? Since I don't have the permissions.

**Review by JoeOster — APPROVED** [review]
approved for CI only

**Comment by JoeOster** [comment]
@tyoungsc are these expected errors for 2021.3 ci?

**Comment by tyoungsc** [comment]
@ajaykumarkannan can you comment? I didn't think that CL/sycl.hpp changed at all from 2021.3 to 2021.4? Wouldn't we see this error in all other designs?

**Comment by ajaykumarkannan** [comment]
I’ve been looking into this. This particular error is expected, but I noticed another issue with the sycl RTL flow that I’m still digging into. I’ll post an update once I know for sure.

**Comment by mdbtucker** [comment]
@ajaykumarkannan I believe this PR is dead now, since the sample has been removed?  Closing the PR, pleas reopen if I'm incorrect.

**Pull request closed without merging**
