### PR TITLE
Simple CUDA Graph migration sample

### PR DESCRIPTION
**Pull request by ShwethaSelma**
# Adding a New Sample(s)

## Description

SimpleCudaGraphs migration from CUDA to SYCL and mapping of Taskflow API's to CUDA Graph API's.

## Checklist
Administrative
- [X] Review sample design with the appropriate [Domain Expert](https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts): Choudary, Chekuri; Krishnappa, Rakshith
- [ ] If you have any new dependencies/binaries, inform the oneAPI Code Samples Project Manager

Code Development
- [X] Implement coding guidelines and ensure code quality. [see wiki for details](https://github.com/oneapi-src/oneAPI-samples/wiki/General-Code-Guidelines)
- [X] Adhere to readme template 
- [X] Enforce format via clang-format config file
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com

Security and Legal
- [ ] OSPDT Approval (see Project Manager for assistance)
- [X] Compile using the following compiler flags and fix any warnings, the falgs are: "/Wall -Wformat-security -Werror=format-security"
- [ ] Bandit Scans (Python only)
- [ ] Virus scan

Review
- [X] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [X] Review readme with Tom Lenth(@tomlenth) and/or Project Manager
- [X] Tested using Dev Cloud when applicable

### CODE REVIEW

**Comment by jimmytwei** [comment]
Adding @jkinsky and @ishaghosh27 for README review.

**Comment by jimmytwei** [comment]
@ShwethaSelma Verified sample builds and runs. Please incorporate @jkinsky feedback to the sample and then I will approve and merge it.

**Comment by ShwethaSelma** [comment]
> @ShwethaSelma Verified sample builds and runs. Please incorporate @jkinsky feedback to the sample and then I will approve and merge it.

I have incorporated the comment and updated the sample name in sample.json file.

**Comment by jimmytwei** [comment]
@ShwethaSelma I think the sample name should be something more descriptive than "SimpleCudaGraphs Sample". Adding @tomlenth and @jkinsky for feedback.

Also, it is missing the expertise field in sample.json. Adding @ishaghosh27 for feedback.

**Comment by jkinsky** [comment]
> @ShwethaSelma I think the sample name should be something more descriptive than "SimpleCudaGraphs Sample". Adding @tomlenth and @jkinsky for feedback.
> 
> Also, it is missing the expertise field in sample.json. Adding @ishaghosh27 for feedback.

Agree. At the very least, you should change the name in the readme and sample.json files to "Simple Cuda Graphs" Sample. Adding spaces will make it better even if you don't change the name completely.

**Comment by ishaghosh27** [comment]
@ShwethaSelma @jimmytwei Please add Expertise: Code Optimization to the sample.json file.

**Comment by ShwethaSelma** [comment]
> > @ShwethaSelma I think the sample name should be something more descriptive than "SimpleCudaGraphs Sample". Adding @tomlenth and @jkinsky for feedback.
> > Also, it is missing the expertise field in sample.json. Adding @ishaghosh27 for feedback.
> 
> Agree. At the very least, you should change the name in the readme and sample.json files to "Simple Cuda Graphs" Sample. Adding spaces will make it better even if you don't change the name completely.

I have changed the name as suggested.

**Comment by ShwethaSelma** [comment]
> Concept and Functionality"

Updated.

**Pull request merged**
