### PR TITLE
Added sample for LiDAR-based object detection with PointPillars

### PR DESCRIPTION
**Pull request by fabianoboril**
# Description
This PR adds a new sample based for LiDAR-based object detection using PointPillars

## Type of change
- [x] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line (as described in README)
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [ ] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [ ] Implement coding guidelines and ensure code quality.
- [ ] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [x] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [ ] Adhere to readme template 
- [ ] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [x] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [x] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [x] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

### CODE REVIEW

**Review by JoeOster — CHANGES_REQUESTED** [review]
Please add the .clang-format to the ignore list

**Review by pmpeter1 — COMMENTED** [review]
The code has a somewhat consistent style.   It diverges from the naming style used for the DirectCoding samples.  

There is a lot of DPCT usage illustrated here.     Is that on purpose?   

For open source applications like this that are "ported" to oneAPI, it may be necessary to create a new category for them.

**Review by JoeOster — CHANGES_REQUESTED** [review]
Please review comments by pmpeter1,

**Comment by fabianoboril** [comment]
Hi Peter,

thanks for your input.

> 
> 
> The code has a somewhat consistent style. It diverges from the naming style used for the DirectCoding samples.
> 
> There is a lot of DPCT usage illustrated here. Is that on purpose?
> 
> For open source applications like this that are "ported" to oneAPI, it may be necessary to create a new category for them.

The illustration of DPCT use is in fact intended. If necessary, we can also create a new category, if you think that this might make sense. Do you have any suggestion?

Regarding the naming style: Yes, we diverge. The reason is that this code is derived from an existing opensource library. In order to be able to understand the differences, follow the code structure, etc., we believe that maintaining the original naming style will help people. Please let us know, if we should refactor the code.

**Comment by JoeOster** [comment]
Currently discussing route forward due to the use of DPCT coding style, closing PR until its resolved

**Pull request closed without merging**
