### PR TITLE
a note for limitation of freeze_optimize_v2.py

### PR DESCRIPTION
**Pull request by louie-tsai**
# Existing Sample Changes
## Description

add a note to bring up a limitation of freeze_optimize_v2.pu

Fixes Issue# 
https://jira.devtools.intel.com/browse/TFDO-5220

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Review by praveenkk123 — DISMISSED** [review]
Approve for CI

**Comment by louie-tsai** [comment]
LPOT changed its name to INC. 
Modified LPOT related sections accordingly.
please help me to run the CI for the changes.

**Review by praveenkk123 — APPROVED** [review]
Approve for CI

**Comment by louie-tsai** [comment]
thanks for starting CI testings. please help me to merge the PR if it looks good to you.

**Pull request merged**
