### PR TITLE
changes for oneccl 2021.6 release

### PR DESCRIPTION
**Pull request by louie-tsai**
# Existing Sample Changes
## Description
changes for oneccl 2021.6 release

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Review by tomlenth — APPROVED** [review]

**Comment by louie-tsai** [comment]
This is for 2021.6 release, and it will fail at 2021.5 release.
please re-test it again once we have 2022.2 installation in CI machine.

**Comment by louie-tsai** [comment]
this change depends on 2021.6 release which is released from 2022.2 BaseKit.
image

I am checking whether it is expected result from oneCCL team, and will keep you posted.

regards
Louie

**Comment by louie-tsai** [comment]
According to oneCCL team, oneCCL samples need L0 software packages.
https://github.com/oneapi-src/oneCCL#prerequisites
Could we make sure to have those L0 software packages installed in CI machines?

thanks

**Comment by louie-tsai** [comment]
it works on nntcl15-nuc.inn.intel.com with level zero packages
image

**Review by praveenkk123 — APPROVED** [review]

**Pull request merged**
