### PR TITLE
Revisited Jacobi_CUDAGraph SYCL Migration sample

### PR DESCRIPTION
**Pull request by ShwethaSelma**
# Existing Sample Changes
## Description

Revisited the Jacobi CUDAGraph Migration Sample, updated with latest version of SYCLomatic Tool and Toolkit. 
## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [X] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by jimmytwei** [comment]
Added @jkinsky to review the README.

@ShwethaSelma Just to confirm... are you removing the guided_jacobi_SYCLMigration folder and adding in the guided_jacobi_CudaGraphs_SYCLMigration folder in the PR?

**Comment by ShwethaSelma** [comment]
> Added @jkinsky to review the README.
> 
> @ShwethaSelma Just to confirm... are you removing the guided_jacobi_SYCLMigration folder and adding in the guided_jacobi_CudaGraphs_SYCLMigration folder in the PR?

Yes @jkinsky, We are revisiting the Migration sample and migrating them with the latest tool, and updating the Readme with new format.

**Review by jkinsky — APPROVED** [review]

**Comment by jimmytwei** [comment]
@ShwethaSelma Are there any specific HW requirements to run the sample?
Also I'm getting one of these error messages when running `make run1`

```
terminate called after throwing an instance of 'sycl::_V1::exception'
  what():  Required aspect atomic64 is not supported on the device
```

**Comment by ShwethaSelma** [comment]
> @ShwethaSelma Are there any specific HW requirements to run the sample? Also I'm getting one of these error messages when running `make run1`
> 
> ```
> terminate called after throwing an instance of 'sycl::_V1::exception'
>   what():  Required aspect atomic64 is not supported on the device
> ```

@jimmytwei need the HW to have double data type support which is taken care in the code, other than that i haven't found any. Sample runs fine on Gen9/Gen11 and on Xeon CPU.  

On which device this error is encountered?

**Comment by jimmytwei** [comment]
@ShwethaSelma Thanks, I'll try to rerun on a Xeon. Is there any specific Xeon that I need to run this on and also any extensions required?

**Comment by ShwethaSelma** [comment]
> @ShwethaSelma Thanks, I'll try to rerun on a Xeon. Is there any specific Xeon that I need to run this on and also any extensions required?

I had ran  it on Intel(R) Xeon(R) Gold 6128 CPU @ 3.40GHz.

**Pull request merged**
