### PR TITLE
ApplicationDebugger/array-transform: fine-tune README

### PR DESCRIPTION
**Pull request by barisaktemur**
# Description

1. Update the debugger name and add trademark note.

2. Update the compiler name.

3. Fine-tune spacing of the table.

4. Refer to the Get Started Guide for details.

5. Update the examples outputs.

### CODE REVIEW

**Comment by tomlenth** [comment]
A couple of comments regarding the README: 
-Before the Example Output section, include a the heading Running the Sample.  this may also be a good place to introduce GDB and how the sample should be used with the debugger. 
- Similarly, the "Useful Commands" section is a great additoin, but needs more context.  I ran into this in the Getting Started Guide for GDB as well.  We don't ever tell the user when/how to start GDB.  It would be ideal to precede this section with something like "Type the following to invoke the debugger," it may seem obvious, but no where in the readme or Getting Started to we tell the user this and instead we just provide commands out of context.  
-lastly, I may try to introduce a more standard section regarding setvars.  although having it step one is front and center, this gets problematic if every sample starts with this since the script will generate warning on subsequent runs.  nothing to change for now, but be aware we may change this.

**Review by JoeOster — APPROVED** [review]

**Review by JoeOster — CHANGES_REQUESTED** [review]
Waiting for Toms suggestions to be addressed

**Review by anjgola — DISMISSED** [review]

**Comment by JoeOster** [comment]
@barisaktemur - Please take a look at the comments by TomLenth and address as appropriate

**Comment by tomlenth** [comment]
Baris and I had an offline discussion.  instead of explicitly telling the user to start gdb, we'll point the user to the OS specific GDB getting started guide at the end of each OS specific section of the readme.  This is much more comprehensive and ensures that the user has additional context needed to use the sample.  The link to the GSGs can be positioned as the last step in in build/run section. We've had good luck with this metaphor in the past as the explicit call to action.

**Review by JoeOster — APPROVED** [review]

**Comment by anjgola** [comment]
Pending @tomlenth  approval for merge.

**Comment by tomlenth** [comment]
this works for me.  thank you for including this.

**Pull request merged**
