### PR TITLE
Removing dependency on libsycl-complex.o so that it runs on level 0 and CPU

### PR DESCRIPTION
**Pull request by varsha-madananth**

### CODE REVIEW

**Comment by anjgola** [comment]
@mkitez  Can you please investigate what happened here. Why are old test result comments showing up on a new PR.

**Comment by anjgola** [comment]
LGTM but there is a infrastructure problem that this PR is showing. Let us not approve or change the state of this PR before Roman has had a chance to look as such situations are hard to recreate.

**Comment by mkitez** [comment]
@anjgola note that comments are showing up not for a PR but for specific commits. It looks like this PR includes some old commits from Varsha's repository which have already been validated. I suggest that Varsha gets her fork in sync with this repo and then re-create the PR.

**Comment by varsha-madananth** [comment]
Closing this request and creating a new one.

**Pull request closed without merging**
