### PR TITLE
Attempt to restore Windows support to FPGA samples facing long-path issues

### PR DESCRIPTION
**Pull request by akertesz**
# Description

Windows support for two FPGA tutorial code samples (loop_unroll and fpga_reg) had to be pulled due to unexpected long path failures in the GitHub CI tests. Recently, a third FPGA code sample (remove_loop_carried_dependency) began failing with the same signature. Non of these failures can be reproduced when tested locally.

This PR exists to trigger the CI tests so that we reproduce the issue on the test machine and debug it further.

Please do not merge yet.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

- [x] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

### CODE REVIEW

**Review by anjgola — APPROVED** [review]

**Comment by akertesz** [comment]
Of the three affect code samples, there remains a CI machine long path issue on Windows for just one.

Reopening this for further investigation...

**Comment by anjgola** [comment]
If this is not being worked on, please close this PR and create another when there is work in progress. If you just need a PR to view differences please create it in your fork instead of here.

**Comment by akertesz** [comment]
@anjgola -- This exists as a roundabout method to gain access to the test machine for experimenting. Is it ok if we leave it open a bit longer?

**Comment by akertesz** [comment]
The tests aren't launching... I'm guessing because the branch is too stale to merge? I'll close it.

**Comment by akertesz** [comment]
Root cause understood now, closing this.

**Pull request closed without merging**
