### PR TITLE
Add sample json

### PR DESCRIPTION
**Pull request by JoeOster**
# Description

Need to add sample.json to several jupyter notebooks, at one-time automation wasn't scanning, but now can. So needed to add

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by mdbtucker** [comment]
Joe, a few issues with this one:

1. I believe the point of this review was to validate the sample.json that you're adding, but the validation seems to have failed.
2. You seem to have accidentally added back the file you deleted in the last change I approved, please make sure you clean that up before merging.
3. It looks like you created a new branch for this merge as we discussed, but you still have 150 changes in your history.  Presumably you created the new branch based off the 'master' branch in your fork?  I guess you need to make your fork master branch match origin master branch, or create the new branch off of origin master instead of off of master in your fork?  I'm afraid I don't have much experience with forked repositories so I'm not sure what the correct procedure is.  If you sort it out please let me know :-)

**Review by mdbtucker — CHANGES_REQUESTED** [review]
Sorry, getting used to the UI here.  See my previous comment.

**Comment by JoeOster** [comment]
> Sorry, getting used to the UI here. See my previous comment.
#1 - failed like I was suspecting, I will be getting it resolved
#2 will be resolved when the other PR gets merged, in the next day or two. 
#3, yea I need to get that cleaned up

**Review by mdbtucker — DISMISSED** [review]
Approving on the assumption that this latest change fixes the CI problem.

**Comment by JoeOster** [comment]
stopped this path

**Pull request closed without merging**
