### PR TITLE
[SYCL joint matrix] Improve the test to include the runtime query

### PR DESCRIPTION
**Pull request by dkhaldi**
# Updated  oneAPI-samples/Publications/GPU-Opt-Guide/joint-matrix/joint-matrix.cpp

## Description
Update the test to match recent changes in the GPU optimization guide.

## External Dependencies
GPU optimization guide 

## Type of change
- [X] New feature (non-breaking change which adds functionality): Add runtime query usage in the test

## How Has This Been Tested?
tested on PVC machine 
icpx -fsycl joint-matrix.cpp
./a.out

### CODE REVIEW

**Comment by dkhaldi** [comment]
@zma2, can you please review?

**Review by zma2 — COMMENTED** [review]
looks good to me

**Comment by zma2** [comment]
@jimmytwei  Can you please review and merge this PR? This is an improvement of an existing sample.

**Comment by jimmytwei** [comment]
@zma2 Can you or @dkhaldi submit this to `development` branch?

**Comment by jimmytwei** [comment]
Closing this PR as I made the changes directly in the `development` branch.

**Pull request closed without merging**
