### PR TITLE
Fixed iota in FPGA pipes tutorial

### LINKED ISSUE #903: Creating input data with std::iota in FPGA pipes tutorial has bug
# Summary
The following change should be made to _DirectProgramming/DPC++FPGA/Tutorials/Features/pipes/src/pipes.cpp_:

Current:
```cpp
std::iota(producer_input.begin(), producer_input.begin(), 0);
```

Change:
```cpp
std::iota(producer_input.begin(), producer_input.end(), 0);
```

### PR DESCRIPTION
**Pull request by tyoungsc**
# Existing Sample Changes
## Description
Fixing a host call to std::iota in the FPGA pipes tutorial. Previously the call to iota didn't actually initialize anything.

Fixes #903 

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
- [X] Command Line

### CODE REVIEW

**Comment by mdbtucker** [comment]
Any explanation for the Linux emulation failure in the CI?

**Comment by tyoungsc** [comment]
> Any explanation for the Linux emulation failure in the CI?

Nope :/

**Comment by tyoungsc** [comment]
> Any explanation for the Linux emulation failure in the CI?

I was not able to replicate this locally with the same SYCL resource (I tried the trunk and release branch of 20211123). I will try making another change to relaunch the CI. Interestingly, it passed on Windows.

**Comment by mdbtucker** [comment]
@tyoungsc you indicated elsewhere that the CI issues have been resolved - can you make a simple change so the CI will be re-triggered here so we can see that?  (I'm sure there are other ways to trigger the CI, but I don't know what they are)

**Comment by tyoungsc** [comment]
> @tyoungsc you indicated elsewhere that the CI issues have been resolved - can you make a simple change so the CI will be re-triggered here so we can see that? (I'm sure there are other ways to trigger the CI, but I don't know what they are)

Done

**Review by mdbtucker — APPROVED** [review]

**Pull request merged**
