### PR TITLE
 Github repo and DevCloud better integration

### PR DESCRIPTION
**Pull request by krzeszew**
# Existing Sample Changes
## Description

The DevCloud uses a batch system for processing. To get the samples to run, users need to know how to create the script or know how to request an interactive mode.

To make it easier for DevCloud users to run the sample, I created scripts to build (build.sh) and run (run.sh) on DevCloud. Proper documentation explaining the process has been added to README.md.

In the hidden-markov-models example, there have been some major changes to the documentation. We decided to create separate scripts instead of explaining to users how to do it themselves. This makes it easier for the user to run the samples right after connecting to DevCloud using only one command and it improves the UX

This change  will be later followed by others for the remaining samples

## External Dependencies

List any external dependencies created as a result of this change.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line

### CODE REVIEW

**Comment by krzeszew** [comment]
@bdmoore1 please take a look at the documentation change.

**Review by bdmoore1 — DISMISSED** [review]
@krzeszew These changes all look good to me. One question, does the modification of the build.sh and run.sh scripts have any conflict with what the VS Code DevCloud Connector extension that allows users to request a specific device on a compute node? 
Details are here, under section 1.3: https://devcloud.intel.com/oneapi/get_started/baseToolkitSamples/

**Comment by krzeszew** [comment]
@bdmoore1 The changes should not conflict with the VS Code extension. The scripts are send to the queue and run in batch mode. They immediately have a defined compute machine on which they will run due to the fact that it is necessary to use special commands to build and run the sample on a proper compute node such as fpga emulator. 
This is shown in the link you sent in section 2.1 (Build and run the sample in batch mode).

**Comment by bdmoore1** [comment]
@krzeszew I approve this PR, but I think you need a reviewer with administrator status to merge. You might need to add @praveenkk123  or someone else to this review.

**Comment by krzeszew** [comment]
@praveenkk123 could you please take a look?

**Comment by krzeszew** [comment]
Updated commit to the current master and resolved readme files merge conflicts.

**Review by bdmoore1 — APPROVED** [review]

**Review by jimmytwei — DISMISSED** [review]

**Comment by krzeszew** [comment]
Rebase on origin/master and resolve merging conflicts.

**Review by jimmytwei — APPROVED** [review]

**Pull request merged**
