### PR TITLE
modify Q script for the latest DevCloud and add sanity check

### PR DESCRIPTION
**Pull request by louie-tsai**
# Existing Sample Changes
## Description

modify Q script for the latest DevCloud and add sanity check

## External Dependencies

no

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Implement fixes for ONSAM Jiras

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode
- [ ] When compiling the compliler flag "-Wall -Wformat-security -Werror=format-security" was used

### CODE REVIEW

**Comment by louie-tsai** [comment]
this is for the latest devcloud.

**Comment by louie-tsai** [comment]
@praveenkk123 
could you help to merge the PR for the latest DevCloud?

**Comment by louie-tsai** [comment]
Hi 
NDA AI kit users might need to this PR when they follow our GSG below.
https://wiki.ith.intel.com/display/ts/NDA+AI+Kit#NDAAIKit-DevCloud
please help to merge the PR.

thanks

**Comment by louie-tsai** [comment]
Hi 
We need this PR for NDA AI Kit.
Could you merge it?

**Review by jimmytwei — APPROVED** [review]

**Pull request merged**
