### PR TITLE
Add sample.json and files for automated testing

### PR DESCRIPTION
**Pull request by karlqi2000**
Signed-off-by: Karl Qi <karl.qi@intel.com>

## Description

Add sample.json and relevant files to enable automated testing.

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 
- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?
- [X] Command Line

### CODE REVIEW

**Review by JoeOster — APPROVED** [review]
approved for ci runonly

**Comment by karlqi2000** [comment]
Is there anything else I need to do for this merge? Thanks

**Review by JoeOster — APPROVED** [review]
approved for ci only

**Review by JoeOster — CHANGES_REQUESTED** [review]
Makefiles should only be used for Darwin or Darwin/linux samples. If linux, use cmake

As to the issue with the sample.json file, take a look at the [openOMP reduction](https://github.com/oneapi-src/oneAPI-samples/tree/bed8a563ace4a31d00a4f1055f65d680fa4fe0a8/DirectProgramming/C%2B%2B/ParallelPatterns/openmp_reduction) sample for some ideas. I suspect a change

I will be looking into the fix issue

**Review by JoeOster — APPROVED** [review]

**Pull request merged**
