### PR TITLE
Jupyter Notebook training for GPU Optimization Guide

### PR DESCRIPTION
**Pull request by krisrak**
# Existing Sample Changes
## Description

Adding Jupyter Notebook training for GPU Optimization training, code samples used is from GPU Optimization guide document.

## External Dependencies

NA

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
make
make run
make clean

### CODE REVIEW

**Comment by jimmytwei** [comment]
@jkinsky @tomlenth I'm back and going through all the PRs... has Rakshith reviewed this with either of you already?

**Review by tomlenth — CHANGES_REQUESTED** [review]
minor issue.  the license text should be moved to end of readme to be consistent with other samples.  in fact, it should be at the bottom of the root readme, but dropped from subpages.

**Comment by tomlenth** [comment]
@jimmytwei , I'm not familiar with this particular one.  And, I think there may be some of the sycl migration samples that have not "officially" been reviewed in the WG.  These may not have made it onto the dashboard either.  I'm having trouble wading through a lot of the git notifications to sort through what's what.

**Comment by jkinsky** [comment]
These top-level Jupyter Notebook readmes are kind of unique. This is a better example of the structure for these types of top-level readmes: https://github.com/oneapi-src/oneAPI-samples/blob/development/AI-and-Analytics/Jupyter/Predictive_Modeling_Training/README.md. The readme.md in this PR is close to the final structure needed, but it could be updated to match the example more.

**Comment by jimmytwei** [comment]
@praveenkk123 @jkinsky I've updated all of the READMEs and moved the License section to the bottom.

**Pull request merged**
