### PR TITLE
Add iLiT sampe for Tensorflow

### PR DESCRIPTION
**Pull request by NeoZhangJianyu**
# Description

Add iLiT sampe for Tensorflow

## Type of change

Please delete options that are not relevant. Add a 'X' to the one that is applicable. 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Sample Migration (Moving sample from old repository after completing checklist established)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [X] Command Line
- [ ] oneapi-cli
- [ ] Visual Studio
- [ ] Eclipse IDE
- [ ] VSCode

# Checklist for Moving samples:
Links and Details can be found in the samples WG Teams Files. 

- [X] Review sample design with domain reviewers https://github.com/oneapi-src/oneAPI-samples/wiki/Reviewers-and-Domain-Experts 
- [X] Implement coding guidelines and ensure code quality.
- [X] Adhere to sample.json specification. https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-specification
- [X] Run jsonlint on sample.json to verify json syntax. www.jsonlint.com
- [X] Adhere to readme template 
- [X] Ensure/create CI test configurations for sample (ciTests field) https://github.com/oneapi-src/oneAPI-samples/wiki/sample-json-ci-test-object
- [ ] Enforce format via clang-format config file
- [ ] Review DPC++ code with Paul Peterseon. (GitHub User: pmpeter1)
- [ ] Review readme with Tom Lenth or Joe Oster. (GitHub User: JoeOster)
- [ ] Tested using Dev Cloud when applicable
- [ ] Implement fixes for ONSAM Jiras
- [ ] If you have new dependencies/binaries, inform Samples Project Manager Swapna R Dontharaju (@srdontha) or @JoeOster

### CODE REVIEW

**Review by JoeOster — APPROVED** [review]
approving for ci validation

**Comment by NeoZhangJianyu** [comment]
fix the issue to block CI

**Review by anjgola — APPROVED** [review]

**Review by anjgola — APPROVED** [review]
Trigger CI

**Review by JoeOster — CHANGES_REQUESTED** [review]
I will need a bandit report before I can approve it. This should be run after all other changes have been made,

See Bandit GitHub for pip install and other details: https://github.com/PyCQA/bandit
To run bandit: “bandit -r path/to/your/code”

**Comment by NeoZhangJianyu** [comment]
bandit -r iLiT-Sample-for-Tensorflow
[main]	INFO	profile include tests: None
[main]	INFO	profile exclude tests: None
[main]	INFO	cli include tests: None
[main]	INFO	cli exclude tests: None
[main]	INFO	running on Python 3.7.7
Run started:2020-09-30 01:15:47.404360

Test results:
	No issues identified.

Code scanned:
	Total lines of code: 133
	Total lines skipped (#nosec): 0

Run metrics:
	Total issues (by severity):
		Undefined: 0.0
		Low: 0.0
		Medium: 0.0
		High: 0.0
	Total issues (by confidence):
		Undefined: 0.0
		Low: 0.0
		Medium: 0.0
		High: 0.0
Files skipped (0):

**Review by anjgola — APPROVED** [review]

**Review by JoeOster — APPROVED** [review]
All python scrips must be scanned with Bandit - This has been done

**Pull request merged**
