### PR TITLE
[oneMKL][RNG] rework monte carlo pi device sample

### PR DESCRIPTION
**Pull request by aelizaro**
# Description

Rework monte carlo pi sample for oneMKL RNG. Changed sicl::ONEAPI::reduce approach to atomics

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] Command Line

### CODE REVIEW

**Review by anjgola — DISMISSED** [review]
Triggering CI

**Review by JoeOster — APPROVED** [review]
approving for ci

**Comment by aelizaro** [comment]
There is the same CI issue on windows as in https://github.com/oneapi-src/oneAPI-samples/pull/406 as I understand

**Review by JoeOster — CHANGES_REQUESTED** [review]
We are getting build errors, do you recognize the errors above? I suspect an environmental issue, but not positive

**Comment by aelizaro** [comment]
@JoeOster, I have fixed some issues and aligned makefiles with the rest of domain. Could you, please, rerun CI to check? I ran nmake locally on windows, works fine.

**Review by JoeOster — APPROVED** [review]

**Review by JoeOster — CHANGES_REQUESTED** [review]
after the last round of changes, the Linux runs are now failing

**Comment by aelizaro** [comment]
@JoeOster, which compiler version is used for the CI? If the latest one, I assume new failures may be caused by compiler switch from -mkl to -qmkl

**Review by JoeOster — APPROVED** [review]
approve to pul in ci report, I manually re-run ci earlier passed,just no ticket update

**Pull request merged**
